import type { SpaceConfig } from "../types.js"

export const MACHER_MAP: SpaceConfig = {
  id: "macher-map",
  name: "Macher-Map",
  tagline: "Die Karte der Macher",
  description: "Finde Werkstätten, Events und Projekte in deiner Nähe. Werde Teil der Macher-Community.",
  domain: "macher-map.de",

  modules: [
    { moduleId: "dashboard", label: "Start", icon: "LayoutGrid", order: 0 },
    { moduleId: "map", label: "Karte", icon: "Map", order: 1 },
    { moduleId: "werkstaetten", label: "Werkstätten", icon: "Hammer", order: 2 },
    { moduleId: "calendar", label: "Events", icon: "CalendarDays", order: 3 },
    { moduleId: "projects", label: "Projekte", icon: "Rocket", order: 4 },
    { moduleId: "gamification", label: "Skills", icon: "Flame", order: 5 },
    { moduleId: "profile", label: "Profil", icon: "User", order: 6 },
  ],

  theme: {
    colors: {
      primary: "#E8751A",
      secondary: "#D4A020",
      accent: "#45B764",
      background: "#FFFAF5",
      surface: "#FFFFFF",
      text: "#1A1A1A",
      muted: "rgba(10,10,10,0.5)",
      danger: "#DC2626",
      success: "#45B764",
      warning: "#D4A020",
    },
    categoryColors: {
      holz: "#C4883C",
      metall: "#7A8B99",
      elektro: "#2D7DD2",
      elektronik: "#2D7DD2",
      digital: "#2D7DD2",
      "3ddruck": "#2D7DD2",
      cnc: "#2D7DD2",
      laser: "#2D7DD2",
      textil: "#C07090",
      naehen: "#C07090",
      keramik: "#B06840",
      toepfern: "#B06840",
      schmieden: "#E8751A",
      fahrrad: "#45B764",
      reparatur: "#45B764",
      siebdruck: "#9B59B6",
      lehm: "#8B7355",
      modellbau: "#E0A050",
    },
    fonts: {
      heading: "Space Grotesk",
      body: "Inter",
      mono: "JetBrains Mono",
    },
    iconSet: "lucide",
    radius: "lg",
    mapStyle: {
      tileUrl: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
      attribution: "CartoDB",
      pinStyle: "teardrop",
      clusterStyle: "ring",
    },
    terms: {
      werkstatt: "Werkstatt",
      event: "Event",
      user: "Macher",
      project: "Projekt",
      badge: "Abzeichen",
      skill: "Fähigkeit",
      leaderboard: "Rangliste",
      join: "Beitreten",
      create: "Erstellen",
      profile: "Profil",
    },
  },

  itemTypes: [
    {
      type: "werkstatt",
      label: "Werkstatt",
      labelPlural: "Werkstätten",
      icon: "Hammer",
      color: "#E8751A",
      fields: [
        { key: "title", type: "text", label: "Name", required: true, placeholder: "z.B. Holzwerkstatt Kreuzberg" },
        { key: "description", type: "richtext", label: "Beschreibung", required: false },
        { key: "location", type: "location", label: "Standort", required: true },
        { key: "tags", type: "tags", label: "Kategorien", required: false, placeholder: "holz, metall, elektro..." },
        { key: "category", type: "select", label: "Hauptkategorie", required: true,
          options: ["holz", "metall", "elektro", "textil", "keramik", "schmieden", "fahrrad", "siebdruck", "laser", "reparatur", "3ddruck", "digital"] },
      ],
      appearsIn: ["map", "feed", "dashboard"],
      actions: ["create", "edit", "delete", "join", "leave", "share"],
      pinStyle: { shape: "teardrop", size: 44, anchorBottom: true },
    },
    {
      type: "event",
      label: "Event",
      labelPlural: "Events",
      icon: "Zap",
      color: "#E8751A",
      fields: [
        { key: "title", type: "text", label: "Titel", required: true },
        { key: "description", type: "richtext", label: "Beschreibung", required: false },
        { key: "location", type: "location", label: "Ort", required: true },
        { key: "start", type: "datetime", label: "Beginn", required: true },
        { key: "end", type: "datetime", label: "Ende", required: false },
        { key: "eventType", type: "select", label: "Typ", required: true,
          options: ["workshop", "kurs", "bau", "wettbewerb", "treffen", "offen"] },
        { key: "maxParticipants", type: "number", label: "Max. Teilnehmer", required: false },
        { key: "tags", type: "tags", label: "Tags", required: false },
      ],
      appearsIn: ["map", "calendar", "feed", "dashboard"],
      actions: ["create", "edit", "delete", "join", "leave", "share"],
      pinStyle: { shape: "teardrop", size: 38, anchorBottom: true },
    },
    {
      type: "project",
      label: "Projekt",
      labelPlural: "Projekte",
      icon: "Rocket",
      color: "#45B764",
      fields: [
        { key: "title", type: "text", label: "Titel", required: true },
        { key: "description", type: "richtext", label: "Beschreibung", required: false },
        { key: "location", type: "location", label: "Standort", required: true },
        { key: "goalAmount", type: "number", label: "Ziel-Betrag (EUR)", required: false },
        { key: "tags", type: "tags", label: "Tags", required: false },
        { key: "videoUrl", type: "url", label: "Video-URL", required: false },
      ],
      appearsIn: ["map", "feed", "dashboard"],
      actions: ["create", "edit", "delete", "fund", "share"],
      pinStyle: { shape: "teardrop", size: 44, anchorBottom: true },
    },
  ],

  connector: "graphql",

  gamification: {
    skillCategories: [
      { id: "holz", name: "Holz", color: "#C4883C", icon: "TreePine" },
      { id: "metall", name: "Metall", color: "#7A8B99", icon: "Wrench" },
      { id: "elektro", name: "Elektro", color: "#2D7DD2", icon: "Zap" },
      { id: "digital", name: "Digital", color: "#2D7DD2", icon: "Monitor" },
      { id: "textil", name: "Textil", color: "#C07090", icon: "Scissors" },
      { id: "bau", name: "Bau", color: "#E8751A", icon: "Hammer" },
    ],
    badges: [
      { id: "erster-funke", name: "Erster Funke", description: "Erstes Event besucht", icon: "🔥", color: "#E8751A",
        requirement: { type: "items_joined", value: 1 } },
      { id: "macher", name: "Macher", description: "10 Events besucht", icon: "⚡", color: "#D4A020",
        requirement: { type: "items_joined", value: 10 } },
      { id: "werkstatt-gruender", name: "Werkstatt-Gründer", description: "Erste Werkstatt erstellt", icon: "🏗️", color: "#45B764",
        requirement: { type: "items_created", value: 1 } },
      { id: "meister", name: "Meister", description: "Level 10 in einer Kategorie", icon: "👑", color: "#D4A020",
        requirement: { type: "any_skill_level", value: 10 } },
      { id: "allrounder", name: "Allrounder", description: "Level 3 in allen Kategorien", icon: "🌟", color: "#9B59B6",
        requirement: { type: "skills_at_level", value: 3 } },
    ],
    xpRules: [
      { trigger: "item.join", itemType: "event", category: "bau", amount: 25, description: "Event besucht" },
      { trigger: "item.create", itemType: "werkstatt", category: "bau", amount: 100, description: "Werkstatt erstellt" },
      { trigger: "item.create", itemType: "project", category: "bau", amount: 75, description: "Projekt gestartet" },
      { trigger: "connection.confirm", category: "bau", amount: 15, description: "Verbindung bestätigt" },
    ],
    levelFormula: "sqrt",
    levelBase: 50,
  },

  landing: {
    sections: [
      {
        type: "hero",
        headline: "Die Karte der Macher",
        subline: "Finde Werkstätten, Events und Projekte in deiner Nähe. Werde Teil der Community.",
        cta: "Karte entdecken",
        ctaUrl: "/app",
      },
      {
        type: "features",
        items: [
          { title: "Werkstätten finden", description: "Holz, Metall, Elektronik — finde die richtige Werkstatt in deiner Nähe", icon: "Hammer" },
          { title: "Events besuchen", description: "Workshops, Kurse und Bau-Events in deiner Region", icon: "CalendarDays" },
          { title: "Projekte starten", description: "Starte Gemeinschaftsprojekte und finde Unterstützer", icon: "Rocket" },
          { title: "Skills aufbauen", description: "Sammle XP, verdiene Badges und steige im Level", icon: "Flame" },
        ],
      },
      {
        type: "map-preview",
        center: [51.1657, 10.4515],
        zoom: 6,
        demoItems: 50,
      },
      {
        type: "stats",
        items: [
          { label: "Werkstätten", value: "10.000+", icon: "Hammer" },
          { label: "Macher", value: "2.000+", icon: "Users" },
          { label: "Events/Monat", value: "500+", icon: "CalendarDays" },
        ],
      },
      {
        type: "cta",
        headline: "Werde Teil der Macher-Community",
        subline: "Kostenlos. Keine Werbung. Von Machern für Macher.",
        buttonText: "Jetzt mitmachen",
        buttonUrl: "/app",
      },
    ],
    footer: {
      links: [
        { label: "Impressum", url: "/impressum" },
        { label: "Datenschutz", url: "/datenschutz" },
      ],
      legal: "Kollektiv Lichtung e.V.",
    },
  },

  seed: {
    count: 10000,
  },

  meta: {
    author: "Timo + Eli",
    createdAt: "2026-04-28",
    updatedAt: "2026-04-28",
    version: "0.1.0",
    status: "prototype",
  },
}
